### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/ditch#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1 and kevinadhiguna/ip-revealer#1 …

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.  Heck, that last one is a pointless reimplementation of the stock `host` or `nslookup` commands. Even `ping` would do.

**Comment by kevinadhiguna** [comment]
Hi @amcgregor , nice catch ! I did not realize that. The [latest commit](https://github.com/kevinadhiguna/ditch/commit/aade314729c5b8466c51748658cea69e74b616c8) might be able to fix this. If not, please let me know. Big thanks!

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) Wave 2! 😀
